### PR TITLE
bump version to v11.0

### LINKED ISSUE #23: Need to update iverilog to latest stable version (11.0)
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

The latest stable Icarus version is 11.0. We also have enabled CI in our repo for windows so that may be helpful.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

### PR DESCRIPTION
**Pull request by carlodri**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #23

### CODE REVIEW

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
something fishy going on here with library paths, see this error in the windows build (which still makes it through the CI, by the way):
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=257276&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=1874

and this that breaks the osx build in the `make check` phase:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=257276&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=2418

Could be related to this upstream change:
https://github.com/steveicarus/iverilog/commit/41075a45e653793cae25594b1f77246d23c82a35

@tfors do you have any hint here?

**Comment by carlodri** [comment]
@caryr do you have any hint on what's going on here?

**Comment by caryr** [comment]
No, I mostly use Linux, @steveicarus or @martinwhitaker may have a better guess. Given when the upstream change was made I would have expected that to be in 11.0. Maybe there is some Mac subtlety going on. Both Icarus development and V11 are built/tested on Mac as part of our normal CI so it could have something to do with a configuration difference on your build machine that needs to be factored into the change you referenced.

**Comment by martinwhitaker** [comment]
In our CI we run `make install` before `make check`, which is why it passes for us and fails here (we should change that).
I can see what's wrong, and will try to fix it.

**Comment by caryr** [comment]
Since they are trying to release a specific version of Icarus should they instead swap the install/check order? If they use head then this will not track the 11.0 tar file. We could also discuss creating a 11.1 release.

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
I guess this fixes v11 for the time being. The only thing I'm puzzled about is this error message in the windows CI: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=271155&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=1874

@caryr @martinwhitaker do you have any hint? can we safely ignore it?

**Comment by caryr** [comment]
It looks like the library path is not setup correctly. @martinwhitaker any ideas? I don't know if this is just because things have not been fully installed or if this is a real issue. When is this run relative to the make install?

Also I doubt it matters, but as far as I know we never run make install or make check with a -j flag. So these may not have been full checked for weird dependency/order issues.

**Comment by martinwhitaker** [comment]
No idea. configure was run with
````
../configure '--prefix=D:\bld\iverilog_1611952863416\_h_env\Library'
````
so I don't know how it ends up searching in `D:\bld\IVERIL~1\_TEST_~1\Library`. But the install commands look strange too:
````
/usr/bin/install -c ./system.vpi "%PREFIX%\Library/lib/ivl/system.vpi"
````
Where did `%PREFIX%` come from?

**Comment by carlodri** [comment]
probably because conda does some tricks to adapt dependency paths to build/install environment... I'm trying to disable the `-j` flag as per @caryr's comment , let's see what happens

**Comment by carlodri** [comment]
@conda-forge-admin rerender

**Comment by carlodri** [comment]
ok, I'm merging this and will wait if downstream users experience any problems. For reference, the only issue is in the windows build which mysteriously says:

```
error: Failed to open 'D:\bld\IVERIL~1\_TEST_~1\Library\lib\ivl\system.vpi' because:
     : The operation completed successfully.
```

during the `iverilog -v` test.

**Pull request merged**
